import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import masterRouter from "./master";
import inventoryRouter from "./inventory";
import customersRouter from "./customers";
import invoicesRouter from "./invoices";
import quotationsRouter from "./quotations";
import procurementRouter from "./procurement";
import productsRouter from "./products";
import webOrdersRouter from "./web_orders";
import miscRouter from "./misc";
import shopRouter from "./shop";
import storageRouter from "./storage";
import searchRouter from "./search";
import visitorsRouter from "./visitors";
import imeiRouter from "./imei";
import productAiRouter from "./product_ai";
import systemRouter from "./system";
import integrationsRouter from "./integrations";
import activityRouter from "./activity";
import expensesRouter from "./expenses";
import simRouter from "./sim";
import pushRouter from "./push";
import chatRouter from "./chat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(searchRouter);
router.use(visitorsRouter);
router.use(dashboardRouter);
router.use(masterRouter);
router.use(inventoryRouter);
router.use(customersRouter);
router.use(invoicesRouter);
router.use(quotationsRouter);
router.use(procurementRouter);
router.use(productsRouter);
router.use(webOrdersRouter);
router.use(miscRouter);
router.use(shopRouter);
router.use(imeiRouter);
router.use(productAiRouter);
router.use(systemRouter);
router.use(integrationsRouter);
router.use(activityRouter);
router.use(expensesRouter);
router.use(simRouter);
router.use(pushRouter);
router.use(chatRouter);

export default router;
