-- Generated by Geem image updater
-- Run on VPS with: psql $DATABASE_URL -f scripts/update-images.sql
BEGIN;

UPDATE products SET
  featured_image = '/products/security/ajaxhub2/img_1.jpg',
  gallery_images = '["/products/security/ajaxhub2/img_1.jpg","/products/security/ajaxhub2/img_2.jpg","/products/security/ajaxhub2/img_3.jpg","/products/security/ajaxhub2/img_4.jpg","/products/security/ajaxhub2/img_5.jpg"]'
  WHERE slug = 'ajax-hub2-wireless-smart-alarm-starter-kit';

UPDATE products SET
  featured_image = '/products/smartphones/iphone14/img_1.png',
  gallery_images = '["/products/smartphones/iphone14/img_1.png","/products/smartphones/iphone14/img_2.jpg","/products/smartphones/iphone14/img_3.jpg","/products/smartphones/iphone14/img_4.png","/products/smartphones/iphone14/img_5.jpg"]'
  WHERE slug = 'apple-iphone-14-128gb-midnight';

UPDATE products SET
  featured_image = '/products/smartphones/iphone15pro/img_1.jpg',
  gallery_images = '["/products/smartphones/iphone15pro/img_1.jpg","/products/smartphones/iphone15pro/img_2.jpg","/products/smartphones/iphone15pro/img_3.jpg","/products/smartphones/iphone15pro/img_4.jpg"]'
  WHERE slug = 'apple-iphone-15-pro-256gb';

UPDATE products SET
  featured_image = '/products/security/biometric/img_1.png',
  gallery_images = '["/products/security/biometric/img_1.png","/products/security/biometric/img_2.jpg","/products/security/biometric/img_3.jpg","/products/security/biometric/img_4.jpg","/products/security/biometric/img_5.jpg"]'
  WHERE slug = 'biometric-fingerprint-access-controller-rfid';

UPDATE products SET
  featured_image = '/products/covert-comms/throatmic/img_1.jpg',
  gallery_images = '["/products/covert-comms/throatmic/img_1.jpg","/products/covert-comms/throatmic/img_2.jpg","/products/covert-comms/throatmic/img_3.jpg","/products/covert-comms/throatmic/img_4.jpg","/products/covert-comms/throatmic/img_5.jpg"]'
  WHERE slug = 'bone-conduction-throat-microphone-tactical';

UPDATE products SET
  featured_image = '/products/counter-surv/lensfinder/img_1.jpg',
  gallery_images = '["/products/counter-surv/lensfinder/img_1.jpg","/products/counter-surv/lensfinder/img_2.jpg","/products/counter-surv/lensfinder/img_3.png","/products/counter-surv/lensfinder/img_4.png","/products/counter-surv/lensfinder/img_5.jpg"]'
  WHERE slug = 'camera-lens-finder-pinhole-detector';

UPDATE products SET
  featured_image = '/products/rf-detectors/phonedetector/img_1.jpg',
  gallery_images = '["/products/rf-detectors/phonedetector/img_1.jpg","/products/rf-detectors/phonedetector/img_2.jpg","/products/rf-detectors/phonedetector/img_3.jpg","/products/rf-detectors/phonedetector/img_4.png","/products/rf-detectors/phonedetector/img_5.jpg"]'
  WHERE slug = 'cell-phone-detector-unauthorized-mobile';

UPDATE products SET
  featured_image = '/products/covert-comms/earpiece/img_1.jpg',
  gallery_images = '["/products/covert-comms/earpiece/img_1.jpg","/products/covert-comms/earpiece/img_2.jpg","/products/covert-comms/earpiece/img_3.jpg","/products/covert-comms/earpiece/img_4.jpg","/products/covert-comms/earpiece/img_5.jpg"]'
  WHERE slug = 'covert-surveillance-earpiece-kit-single-wire';

UPDATE products SET
  featured_image = '/products/smart-security/dahuanvr/img_1.jpg',
  gallery_images = '["/products/smart-security/dahuanvr/img_1.jpg","/products/smart-security/dahuanvr/img_2.jpg","/products/smart-security/dahuanvr/img_3.jpg","/products/smart-security/dahuanvr/img_4.jpg","/products/smart-security/dahuanvr/img_5.jpg"]'
  WHERE slug = 'dahua-nvr4108hs-8p-4ks3-8ch-poe-nvr';

UPDATE products SET
  featured_image = '/products/security/emlock/img_1.jpg',
  gallery_images = '["/products/security/emlock/img_1.jpg","/products/security/emlock/img_2.jpg","/products/security/emlock/img_3.jpg","/products/security/emlock/img_4.jpg","/products/security/emlock/img_5.jpg"]'
  WHERE slug = 'electromagnetic-door-lock-600lbs';

UPDATE products SET
  featured_image = '/products/covert-comms/pocradio/img_1.jpg',
  gallery_images = '["/products/covert-comms/pocradio/img_1.jpg","/products/covert-comms/pocradio/img_2.jpg","/products/covert-comms/pocradio/img_3.jpg","/products/covert-comms/pocradio/img_4.jpg","/products/covert-comms/pocradio/img_5.jpg"]'
  WHERE slug = 'encrypted-poc-radio-4g-lte-network';

UPDATE products SET
  featured_image = '/products/covert-comms/tacradio/img_1.jpg',
  gallery_images = '["/products/covert-comms/tacradio/img_1.jpg","/products/covert-comms/tacradio/img_2.jpg","/products/covert-comms/tacradio/img_3.jpg","/products/covert-comms/tacradio/img_4.jpg","/products/covert-comms/tacradio/img_5.jpg"]'
  WHERE slug = 'encrypted-tactical-radio-aes256-vhf-uhf';

UPDATE products SET
  featured_image = '/products/counter-surv/gsmdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/gsmdetector/img_1.jpg","/products/counter-surv/gsmdetector/img_2.jpg","/products/counter-surv/gsmdetector/img_3.jpg","/products/counter-surv/gsmdetector/img_4.jpg","/products/counter-surv/gsmdetector/img_5.jpg"]'
  WHERE slug = 'gsm-4g-bug-detector-tap-finder-pro';

UPDATE products SET
  featured_image = '/products/smart-security/hikvcolorvu/img_1.png',
  gallery_images = '["/products/smart-security/hikvcolorvu/img_1.png","/products/smart-security/hikvcolorvu/img_2.png","/products/smart-security/hikvcolorvu/img_3.jpg","/products/smart-security/hikvcolorvu/img_4.jpg","/products/smart-security/hikvcolorvu/img_5.jpg"]'
  WHERE slug = 'hikvision-ds-2cd2t47g2-l-4mp-colorvu';

UPDATE products SET
  featured_image = '/products/smart-security/hikvnvr16/img_1.jpg',
  gallery_images = '["/products/smart-security/hikvnvr16/img_1.jpg","/products/smart-security/hikvnvr16/img_2.jpg","/products/smart-security/hikvnvr16/img_3.jpg","/products/smart-security/hikvnvr16/img_4.jpg","/products/smart-security/hikvnvr16/img_5.jpg"]'
  WHERE slug = 'hikvision-ds-7616ni-m2-16ch-4k-nvr';

UPDATE products SET
  featured_image = '/products/security/hikvintercom/img_1.jpg',
  gallery_images = '["/products/security/hikvintercom/img_1.jpg","/products/security/hikvintercom/img_2.jpg","/products/security/hikvintercom/img_3.jpg","/products/security/hikvintercom/img_4.jpg","/products/security/hikvintercom/img_5.jpg"]'
  WHERE slug = 'hikvision-video-door-intercom-ds-kv8113';

UPDATE products SET
  featured_image = '/products/smartphones/nova12pro/img_1.jpg',
  gallery_images = '["/products/smartphones/nova12pro/img_1.jpg","/products/smartphones/nova12pro/img_2.jpg","/products/smartphones/nova12pro/img_3.jpg","/products/smartphones/nova12pro/img_4.jpg"]'
  WHERE slug = 'huawei-nova-12-pro-256gb';

UPDATE products SET
  featured_image = '/products/lawmate/bu18hd/img_1.jpg',
  gallery_images = '["/products/lawmate/bu18hd/img_1.jpg","/products/lawmate/bu18hd/img_2.jpg","/products/lawmate/bu18hd/img_3.jpg","/products/lawmate/bu18hd/img_4.jpg","/products/lawmate/bu18hd/img_5.jpg"]'
  WHERE slug = 'lawmate-bu-18hd-mini-bullet-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvbc10hd/img_1.jpg',
  gallery_images = '["/products/lawmate/pvbc10hd/img_1.jpg","/products/lawmate/pvbc10hd/img_2.jpg","/products/lawmate/pvbc10hd/img_3.jpg","/products/lawmate/pvbc10hd/img_4.jpg","/products/lawmate/pvbc10hd/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-bc10hd-button-spy-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvcm10i/img_1.jpg',
  gallery_images = '["/products/lawmate/pvcm10i/img_1.jpg","/products/lawmate/pvcm10i/img_2.jpg","/products/lawmate/pvcm10i/img_3.jpg","/products/lawmate/pvcm10i/img_4.jpg","/products/lawmate/pvcm10i/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-cm10i-coffee-mug-spy-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvrc200hd/img_1.png',
  gallery_images = '["/products/lawmate/pvrc200hd/img_1.png","/products/lawmate/pvrc200hd/img_2.jpg","/products/lawmate/pvrc200hd/img_3.png","/products/lawmate/pvrc200hd/img_4.png","/products/lawmate/pvrc200hd/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-rc200hd-car-key-fob-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvwt10i/img_1.jpg',
  gallery_images = '["/products/lawmate/pvwt10i/img_1.jpg","/products/lawmate/pvwt10i/img_2.jpg","/products/lawmate/pvwt10i/img_3.jpg","/products/lawmate/pvwt10i/img_4.jpg","/products/lawmate/pvwt10i/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-wt10i-wristwatch-spy-camera';

UPDATE products SET
  featured_image = '/products/covert-comms/bodyworn/img_1.jpg',
  gallery_images = '["/products/covert-comms/bodyworn/img_1.jpg","/products/covert-comms/bodyworn/img_2.jpg","/products/covert-comms/bodyworn/img_3.jpg","/products/covert-comms/bodyworn/img_4.jpg","/products/covert-comms/bodyworn/img_5.jpg"]'
  WHERE slug = 'mini-covert-body-worn-radio-concealable';

UPDATE products SET
  featured_image = '/products/rf-detectors/bugsweeper/img_1.jpg',
  gallery_images = '["/products/rf-detectors/bugsweeper/img_1.jpg","/products/rf-detectors/bugsweeper/img_2.jpg","/products/rf-detectors/bugsweeper/img_3.jpg","/products/rf-detectors/bugsweeper/img_4.jpg","/products/rf-detectors/bugsweeper/img_5.jpg"]'
  WHERE slug = 'multi-band-bug-sweeper-1mhz-12ghz-professional';

UPDATE products SET
  featured_image = '/products/rf-detectors/nljd/img_1.jpg',
  gallery_images = '["/products/rf-detectors/nljd/img_1.jpg","/products/rf-detectors/nljd/img_2.jpg","/products/rf-detectors/nljd/img_3.jpg","/products/rf-detectors/nljd/img_4.jpg","/products/rf-detectors/nljd/img_5.jpg"]'
  WHERE slug = 'non-linear-junction-detector-nljd';

UPDATE products SET
  featured_image = '/products/security/paradoxsp65/img_1.jpg',
  gallery_images = '["/products/security/paradoxsp65/img_1.jpg","/products/security/paradoxsp65/img_2.jpg","/products/security/paradoxsp65/img_3.jpg","/products/security/paradoxsp65/img_4.jpg","/products/security/paradoxsp65/img_5.jpg"]'
  WHERE slug = 'paradox-sp65-alarm-panel-8-zone';

UPDATE products SET
  featured_image = '/products/spytec/powerbank/img_1.jpg',
  gallery_images = '["/products/spytec/powerbank/img_1.jpg","/products/spytec/powerbank/img_2.jpg","/products/spytec/powerbank/img_3.jpg","/products/spytec/powerbank/img_4.jpg","/products/spytec/powerbank/img_5.jpg"]'
  WHERE slug = 'power-bank-hidden-spy-camera-10000mah';

UPDATE products SET
  featured_image = '/products/counter-surv/rfdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/rfdetector/img_1.jpg","/products/counter-surv/rfdetector/img_2.jpg","/products/counter-surv/rfdetector/img_3.jpg","/products/counter-surv/rfdetector/img_4.jpg","/products/counter-surv/rfdetector/img_5.jpg"]'
  WHERE slug = 'professional-rf-bug-detector-camera-finder';

UPDATE products SET
  featured_image = '/products/smart-security/reolink810a/img_1.jpg',
  gallery_images = '["/products/smart-security/reolink810a/img_1.jpg","/products/smart-security/reolink810a/img_2.jpg","/products/smart-security/reolink810a/img_3.jpg","/products/smart-security/reolink810a/img_4.jpg","/products/smart-security/reolink810a/img_5.jpg"]'
  WHERE slug = 'reolink-rlc-810a-8mp-smart-ip-camera';

UPDATE products SET
  featured_image = '/products/rf-detectors/rfexplorer/img_1.jpg',
  gallery_images = '["/products/rf-detectors/rfexplorer/img_1.jpg","/products/rf-detectors/rfexplorer/img_2.jpg","/products/rf-detectors/rfexplorer/img_3.jpg","/products/rf-detectors/rfexplorer/img_4.jpg","/products/rf-detectors/rfexplorer/img_5.jpg"]'
  WHERE slug = 'rf-explorer-6g-combo-spectrum-analyzer';

UPDATE products SET
  featured_image = '/products/smartphones/a54/img_1.png',
  gallery_images = '["/products/smartphones/a54/img_1.png","/products/smartphones/a54/img_2.png","/products/smartphones/a54/img_3.png","/products/smartphones/a54/img_4.png","/products/smartphones/a54/img_5.png"]'
  WHERE slug = 'samsung-galaxy-a54-5g-128gb';

UPDATE products SET
  featured_image = '/products/smartphones/s24ultra/img_1.jpg',
  gallery_images = '["/products/smartphones/s24ultra/img_1.jpg","/products/smartphones/s24ultra/img_2.jpg","/products/smartphones/s24ultra/img_3.jpg","/products/smartphones/s24ultra/img_4.jpg","/products/smartphones/s24ultra/img_5.jpg"]'
  WHERE slug = 'samsung-galaxy-s24-ultra-256gb';

UPDATE products SET
  featured_image = '/products/smart-security/smartlock/img_1.jpg',
  gallery_images = '["/products/smart-security/smartlock/img_1.jpg","/products/smart-security/smartlock/img_2.jpg","/products/smart-security/smartlock/img_3.jpg","/products/smart-security/smartlock/img_4.jpg","/products/smart-security/smartlock/img_5.jpg"]'
  WHERE slug = 'smart-fingerprint-door-lock-biometric-app';

UPDATE products SET
  featured_image = '/products/spytec/glasses/img_1.jpg',
  gallery_images = '["/products/spytec/glasses/img_1.jpg","/products/spytec/glasses/img_2.jpg","/products/spytec/glasses/img_3.jpg","/products/spytec/glasses/img_4.png","/products/spytec/glasses/img_5.jpg"]'
  WHERE slug = 'spy-glasses-camera-hd-sunglasses';

UPDATE products SET
  featured_image = '/products/spytec/pen/img_1.jpg',
  gallery_images = '["/products/spytec/pen/img_1.jpg","/products/spytec/pen/img_2.jpg","/products/spytec/pen/img_3.jpg","/products/spytec/pen/img_4.jpg","/products/spytec/pen/img_5.jpg"]'
  WHERE slug = 'spy-pen-camera-hd-1080p';

UPDATE products SET
  featured_image = '/products/counter-surv/tapdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/tapdetector/img_1.jpg","/products/counter-surv/tapdetector/img_2.jpg","/products/counter-surv/tapdetector/img_3.jpg","/products/counter-surv/tapdetector/img_4.jpg","/products/counter-surv/tapdetector/img_5.jpg"]'
  WHERE slug = 'telephone-line-tap-detector-scrambler';

UPDATE products SET
  featured_image = '/products/counter-surv/tscmkit/img_1.jpg',
  gallery_images = '["/products/counter-surv/tscmkit/img_1.jpg","/products/counter-surv/tscmkit/img_2.jpg","/products/counter-surv/tscmkit/img_3.png","/products/counter-surv/tscmkit/img_4.jpg","/products/counter-surv/tscmkit/img_5.png"]'
  WHERE slug = 'tscm-sweep-kit-professional';

UPDATE products SET
  featured_image = '/products/spytec/usb/img_1.jpg',
  gallery_images = '["/products/spytec/usb/img_1.jpg","/products/spytec/usb/img_2.jpg","/products/spytec/usb/img_3.png","/products/spytec/usb/img_4.jpg","/products/spytec/usb/img_5.jpg"]'
  WHERE slug = 'usb-flash-drive-spy-camera-1080p';

UPDATE products SET
  featured_image = '/products/spytec/charger/img_1.jpg',
  gallery_images = '["/products/spytec/charger/img_1.jpg","/products/spytec/charger/img_2.png","/products/spytec/charger/img_3.jpg","/products/spytec/charger/img_4.jpg","/products/spytec/charger/img_5.jpg"]'
  WHERE slug = 'usb-wall-charger-spy-camera-wifi';

UPDATE products SET
  featured_image = '/products/spytec/clock/img_1.jpg',
  gallery_images = '["/products/spytec/clock/img_1.jpg","/products/spytec/clock/img_2.jpg","/products/spytec/clock/img_3.jpg","/products/spytec/clock/img_4.jpg","/products/spytec/clock/img_5.jpg"]'
  WHERE slug = 'wall-clock-spy-camera-1080p-wifi';

UPDATE products SET
  featured_image = '/products/rf-detectors/camdetector/img_1.jpg',
  gallery_images = '["/products/rf-detectors/camdetector/img_1.jpg","/products/rf-detectors/camdetector/img_2.jpg","/products/rf-detectors/camdetector/img_3.jpg","/products/rf-detectors/camdetector/img_4.jpg","/products/rf-detectors/camdetector/img_5.jpg"]'
  WHERE slug = 'wireless-hidden-camera-detector-wifi-spy';

UPDATE products SET
  featured_image = '/products/smartphones/xiaomi14pro/img_1.jpg',
  gallery_images = '["/products/smartphones/xiaomi14pro/img_1.jpg","/products/smartphones/xiaomi14pro/img_2.jpg","/products/smartphones/xiaomi14pro/img_3.jpg","/products/smartphones/xiaomi14pro/img_4.jpg"]'
  WHERE slug = 'xiaomi-14-pro-512gb';

COMMIT;
-- End: 42 products updated
