-- Generated by Geem image updater
-- Run on VPS with: psql $DATABASE_URL -f scripts/update-images.sql
BEGIN;

UPDATE products SET
  featured_image = '/products/security/ajaxhub2/img_1.jpg',
  gallery_images = '["/products/security/ajaxhub2/img_1.jpg","/products/security/ajaxhub2/img_2.jpg","/products/security/ajaxhub2/img_3.jpg","/products/security/ajaxhub2/img_4.jpg","/products/security/ajaxhub2/img_5.jpg"]'
  WHERE slug = 'ajax-hub2-wireless-smart-alarm-starter-kit';

UPDATE products SET
  featured_image = '/products/smartphones/iphone14/img_1.png',
  gallery_images = '["/products/smartphones/iphone14/img_1.png","/products/smartphones/iphone14/img_2.jpg","/products/smartphones/iphone14/img_3.jpg","/products/smartphones/iphone14/img_4.png","/products/smartphones/iphone14/img_5.jpg"]'
  WHERE slug = 'apple-iphone-14-128gb-midnight';

UPDATE products SET
  featured_image = '/products/smartphones/iphone15pro/img_1.jpg',
  gallery_images = '["/products/smartphones/iphone15pro/img_1.jpg","/products/smartphones/iphone15pro/img_2.jpg","/products/smartphones/iphone15pro/img_3.jpg","/products/smartphones/iphone15pro/img_4.jpg"]'
  WHERE slug = 'apple-iphone-15-pro-256gb';

UPDATE products SET
  featured_image = '/products/security/biometric/img_1.png',
  gallery_images = '["/products/security/biometric/img_1.png","/products/security/biometric/img_2.jpg","/products/security/biometric/img_3.jpg","/products/security/biometric/img_4.jpg","/products/security/biometric/img_5.jpg"]'
  WHERE slug = 'biometric-fingerprint-access-controller-rfid';

UPDATE products SET
  featured_image = '/products/covert-comms/throatmic/img_1.jpg',
  gallery_images = '["/products/covert-comms/throatmic/img_1.jpg","/products/covert-comms/throatmic/img_2.jpg","/products/covert-comms/throatmic/img_3.jpg","/products/covert-comms/throatmic/img_4.jpg","/products/covert-comms/throatmic/img_5.jpg"]'
  WHERE slug = 'bone-conduction-throat-microphone-tactical';

UPDATE products SET
  featured_image = '/products/counter-surv/lensfinder/img_1.jpg',
  gallery_images = '["/products/counter-surv/lensfinder/img_1.jpg","/products/counter-surv/lensfinder/img_2.jpg","/products/counter-surv/lensfinder/img_3.png","/products/counter-surv/lensfinder/img_4.png","/products/counter-surv/lensfinder/img_5.jpg"]'
  WHERE slug = 'camera-lens-finder-pinhole-detector';

UPDATE products SET
  featured_image = '/products/rf-detectors/phonedetector/img_1.jpg',
  gallery_images = '["/products/rf-detectors/phonedetector/img_1.jpg","/products/rf-detectors/phonedetector/img_2.jpg","/products/rf-detectors/phonedetector/img_3.jpg","/products/rf-detectors/phonedetector/img_4.png","/products/rf-detectors/phonedetector/img_5.jpg"]'
  WHERE slug = 'cell-phone-detector-unauthorized-mobile';

UPDATE products SET
  featured_image = '/products/covert-comms/earpiece/img_1.jpg',
  gallery_images = '["/products/covert-comms/earpiece/img_1.jpg","/products/covert-comms/earpiece/img_2.jpg","/products/covert-comms/earpiece/img_3.jpg","/products/covert-comms/earpiece/img_4.jpg","/products/covert-comms/earpiece/img_5.jpg"]'
  WHERE slug = 'covert-surveillance-earpiece-kit-single-wire';

UPDATE products SET
  featured_image = '/products/smart-security/dahuanvr/img_1.jpg',
  gallery_images = '["/products/smart-security/dahuanvr/img_1.jpg","/products/smart-security/dahuanvr/img_2.jpg","/products/smart-security/dahuanvr/img_3.jpg","/products/smart-security/dahuanvr/img_4.jpg","/products/smart-security/dahuanvr/img_5.jpg"]'
  WHERE slug = 'dahua-nvr4108hs-8p-4ks3-8ch-poe-nvr';

UPDATE products SET
  featured_image = '/products/security/emlock/img_1.jpg',
  gallery_images = '["/products/security/emlock/img_1.jpg","/products/security/emlock/img_2.jpg","/products/security/emlock/img_3.jpg","/products/security/emlock/img_4.jpg","/products/security/emlock/img_5.jpg"]'
  WHERE slug = 'electromagnetic-door-lock-600lbs';

UPDATE products SET
  featured_image = '/products/covert-comms/pocradio/img_1.jpg',
  gallery_images = '["/products/covert-comms/pocradio/img_1.jpg","/products/covert-comms/pocradio/img_2.jpg","/products/covert-comms/pocradio/img_3.jpg","/products/covert-comms/pocradio/img_4.jpg","/products/covert-comms/pocradio/img_5.jpg"]'
  WHERE slug = 'encrypted-poc-radio-4g-lte-network';

UPDATE products SET
  featured_image = '/products/covert-comms/tacradio/img_1.jpg',
  gallery_images = '["/products/covert-comms/tacradio/img_1.jpg","/products/covert-comms/tacradio/img_2.jpg","/products/covert-comms/tacradio/img_3.jpg","/products/covert-comms/tacradio/img_4.jpg","/products/covert-comms/tacradio/img_5.jpg"]'
  WHERE slug = 'encrypted-tactical-radio-aes256-vhf-uhf';

UPDATE products SET
  featured_image = '/products/counter-surv/gsmdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/gsmdetector/img_1.jpg","/products/counter-surv/gsmdetector/img_2.jpg","/products/counter-surv/gsmdetector/img_3.jpg","/products/counter-surv/gsmdetector/img_4.jpg","/products/counter-surv/gsmdetector/img_5.jpg"]'
  WHERE slug = 'gsm-4g-bug-detector-tap-finder-pro';

UPDATE products SET
  featured_image = '/products/smart-security/hikvcolorvu/img_1.png',
  gallery_images = '["/products/smart-security/hikvcolorvu/img_1.png","/products/smart-security/hikvcolorvu/img_2.png","/products/smart-security/hikvcolorvu/img_3.jpg","/products/smart-security/hikvcolorvu/img_4.jpg","/products/smart-security/hikvcolorvu/img_5.jpg"]'
  WHERE slug = 'hikvision-ds-2cd2t47g2-l-4mp-colorvu';

UPDATE products SET
  featured_image = '/products/smart-security/hikvnvr16/img_1.jpg',
  gallery_images = '["/products/smart-security/hikvnvr16/img_1.jpg","/products/smart-security/hikvnvr16/img_2.jpg","/products/smart-security/hikvnvr16/img_3.jpg","/products/smart-security/hikvnvr16/img_4.jpg","/products/smart-security/hikvnvr16/img_5.jpg"]'
  WHERE slug = 'hikvision-ds-7616ni-m2-16ch-4k-nvr';

UPDATE products SET
  featured_image = '/products/security/hikvintercom/img_1.jpg',
  gallery_images = '["/products/security/hikvintercom/img_1.jpg","/products/security/hikvintercom/img_2.jpg","/products/security/hikvintercom/img_3.jpg","/products/security/hikvintercom/img_4.jpg","/products/security/hikvintercom/img_5.jpg"]'
  WHERE slug = 'hikvision-video-door-intercom-ds-kv8113';

UPDATE products SET
  featured_image = '/products/smartphones/nova12pro/img_1.jpg',
  gallery_images = '["/products/smartphones/nova12pro/img_1.jpg","/products/smartphones/nova12pro/img_2.jpg","/products/smartphones/nova12pro/img_3.jpg","/products/smartphones/nova12pro/img_4.jpg"]'
  WHERE slug = 'huawei-nova-12-pro-256gb';

UPDATE products SET
  featured_image = '/products/lawmate/bu18hd/img_1.jpg',
  gallery_images = '["/products/lawmate/bu18hd/img_1.jpg","/products/lawmate/bu18hd/img_2.jpg","/products/lawmate/bu18hd/img_3.jpg","/products/lawmate/bu18hd/img_4.jpg","/products/lawmate/bu18hd/img_5.jpg"]'
  WHERE slug = 'lawmate-bu-18hd-mini-bullet-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvbc10hd/img_1.jpg',
  gallery_images = '["/products/lawmate/pvbc10hd/img_1.jpg","/products/lawmate/pvbc10hd/img_2.jpg","/products/lawmate/pvbc10hd/img_3.jpg","/products/lawmate/pvbc10hd/img_4.jpg","/products/lawmate/pvbc10hd/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-bc10hd-button-spy-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvcm10i/img_1.jpg',
  gallery_images = '["/products/lawmate/pvcm10i/img_1.jpg","/products/lawmate/pvcm10i/img_2.jpg","/products/lawmate/pvcm10i/img_3.jpg","/products/lawmate/pvcm10i/img_4.jpg","/products/lawmate/pvcm10i/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-cm10i-coffee-mug-spy-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvrc200hd/img_1.png',
  gallery_images = '["/products/lawmate/pvrc200hd/img_1.png","/products/lawmate/pvrc200hd/img_2.jpg","/products/lawmate/pvrc200hd/img_3.png","/products/lawmate/pvrc200hd/img_4.png","/products/lawmate/pvrc200hd/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-rc200hd-car-key-fob-camera';

UPDATE products SET
  featured_image = '/products/lawmate/pvwt10i/img_1.jpg',
  gallery_images = '["/products/lawmate/pvwt10i/img_1.jpg","/products/lawmate/pvwt10i/img_2.jpg","/products/lawmate/pvwt10i/img_3.jpg","/products/lawmate/pvwt10i/img_4.jpg","/products/lawmate/pvwt10i/img_5.jpg"]'
  WHERE slug = 'lawmate-pv-wt10i-wristwatch-spy-camera';

UPDATE products SET
  featured_image = '/products/covert-comms/bodyworn/img_1.jpg',
  gallery_images = '["/products/covert-comms/bodyworn/img_1.jpg","/products/covert-comms/bodyworn/img_2.jpg","/products/covert-comms/bodyworn/img_3.jpg","/products/covert-comms/bodyworn/img_4.jpg","/products/covert-comms/bodyworn/img_5.jpg"]'
  WHERE slug = 'mini-covert-body-worn-radio-concealable';

UPDATE products SET
  featured_image = '/products/rf-detectors/bugsweeper/img_1.jpg',
  gallery_images = '["/products/rf-detectors/bugsweeper/img_1.jpg","/products/rf-detectors/bugsweeper/img_2.jpg","/products/rf-detectors/bugsweeper/img_3.jpg","/products/rf-detectors/bugsweeper/img_4.jpg","/products/rf-detectors/bugsweeper/img_5.jpg"]'
  WHERE slug = 'multi-band-bug-sweeper-1mhz-12ghz-professional';

UPDATE products SET
  featured_image = '/products/rf-detectors/nljd/img_1.jpg',
  gallery_images = '["/products/rf-detectors/nljd/img_1.jpg","/products/rf-detectors/nljd/img_2.jpg","/products/rf-detectors/nljd/img_3.jpg","/products/rf-detectors/nljd/img_4.jpg","/products/rf-detectors/nljd/img_5.jpg"]'
  WHERE slug = 'non-linear-junction-detector-nljd';

UPDATE products SET
  featured_image = '/products/security/paradoxsp65/img_1.jpg',
  gallery_images = '["/products/security/paradoxsp65/img_1.jpg","/products/security/paradoxsp65/img_2.jpg","/products/security/paradoxsp65/img_3.jpg","/products/security/paradoxsp65/img_4.jpg","/products/security/paradoxsp65/img_5.jpg"]'
  WHERE slug = 'paradox-sp65-alarm-panel-8-zone';

UPDATE products SET
  featured_image = '/products/spytec/powerbank/img_1.jpg',
  gallery_images = '["/products/spytec/powerbank/img_1.jpg","/products/spytec/powerbank/img_2.jpg","/products/spytec/powerbank/img_3.jpg","/products/spytec/powerbank/img_4.jpg","/products/spytec/powerbank/img_5.jpg"]'
  WHERE slug = 'power-bank-hidden-spy-camera-10000mah';

UPDATE products SET
  featured_image = '/products/counter-surv/rfdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/rfdetector/img_1.jpg","/products/counter-surv/rfdetector/img_2.jpg","/products/counter-surv/rfdetector/img_3.jpg","/products/counter-surv/rfdetector/img_4.jpg","/products/counter-surv/rfdetector/img_5.jpg"]'
  WHERE slug = 'professional-rf-bug-detector-camera-finder';

UPDATE products SET
  featured_image = '/products/smart-security/reolink810a/img_1.jpg',
  gallery_images = '["/products/smart-security/reolink810a/img_1.jpg","/products/smart-security/reolink810a/img_2.jpg","/products/smart-security/reolink810a/img_3.jpg","/products/smart-security/reolink810a/img_4.jpg","/products/smart-security/reolink810a/img_5.jpg"]'
  WHERE slug = 'reolink-rlc-810a-8mp-smart-ip-camera';

UPDATE products SET
  featured_image = '/products/rf-detectors/rfexplorer/img_1.jpg',
  gallery_images = '["/products/rf-detectors/rfexplorer/img_1.jpg","/products/rf-detectors/rfexplorer/img_2.jpg","/products/rf-detectors/rfexplorer/img_3.jpg","/products/rf-detectors/rfexplorer/img_4.jpg","/products/rf-detectors/rfexplorer/img_5.jpg"]'
  WHERE slug = 'rf-explorer-6g-combo-spectrum-analyzer';

UPDATE products SET
  featured_image = '/products/smartphones/a54/img_1.png',
  gallery_images = '["/products/smartphones/a54/img_1.png","/products/smartphones/a54/img_2.png","/products/smartphones/a54/img_3.png","/products/smartphones/a54/img_4.png","/products/smartphones/a54/img_5.png"]'
  WHERE slug = 'samsung-galaxy-a54-5g-128gb';

UPDATE products SET
  featured_image = '/products/smartphones/s24ultra/img_1.jpg',
  gallery_images = '["/products/smartphones/s24ultra/img_1.jpg","/products/smartphones/s24ultra/img_2.jpg","/products/smartphones/s24ultra/img_3.jpg","/products/smartphones/s24ultra/img_4.jpg","/products/smartphones/s24ultra/img_5.jpg"]'
  WHERE slug = 'samsung-galaxy-s24-ultra-256gb';

UPDATE products SET
  featured_image = '/products/smart-security/smartlock/img_1.jpg',
  gallery_images = '["/products/smart-security/smartlock/img_1.jpg","/products/smart-security/smartlock/img_2.jpg","/products/smart-security/smartlock/img_3.jpg","/products/smart-security/smartlock/img_4.jpg","/products/smart-security/smartlock/img_5.jpg"]'
  WHERE slug = 'smart-fingerprint-door-lock-biometric-app';

UPDATE products SET
  featured_image = '/products/spytec/glasses/img_1.jpg',
  gallery_images = '["/products/spytec/glasses/img_1.jpg","/products/spytec/glasses/img_2.jpg","/products/spytec/glasses/img_3.jpg","/products/spytec/glasses/img_4.png","/products/spytec/glasses/img_5.jpg"]'
  WHERE slug = 'spy-glasses-camera-hd-sunglasses';

UPDATE products SET
  featured_image = '/products/spytec/pen/img_1.jpg',
  gallery_images = '["/products/spytec/pen/img_1.jpg","/products/spytec/pen/img_2.jpg","/products/spytec/pen/img_3.jpg","/products/spytec/pen/img_4.jpg","/products/spytec/pen/img_5.jpg"]'
  WHERE slug = 'spy-pen-camera-hd-1080p';

UPDATE products SET
  featured_image = '/products/counter-surv/tapdetector/img_1.jpg',
  gallery_images = '["/products/counter-surv/tapdetector/img_1.jpg","/products/counter-surv/tapdetector/img_2.jpg","/products/counter-surv/tapdetector/img_3.jpg","/products/counter-surv/tapdetector/img_4.jpg","/products/counter-surv/tapdetector/img_5.jpg"]'
  WHERE slug = 'telephone-line-tap-detector-scrambler';

UPDATE products SET
  featured_image = '/products/counter-surv/tscmkit/img_1.jpg',
  gallery_images = '["/products/counter-surv/tscmkit/img_1.jpg","/products/counter-surv/tscmkit/img_2.jpg","/products/counter-surv/tscmkit/img_3.png","/products/counter-surv/tscmkit/img_4.jpg","/products/counter-surv/tscmkit/img_5.png"]'
  WHERE slug = 'tscm-sweep-kit-professional';

UPDATE products SET
  featured_image = '/products/spytec/usb/img_1.jpg',
  gallery_images = '["/products/spytec/usb/img_1.jpg","/products/spytec/usb/img_2.jpg","/products/spytec/usb/img_3.png","/products/spytec/usb/img_4.jpg","/products/spytec/usb/img_5.jpg"]'
  WHERE slug = 'usb-flash-drive-spy-camera-1080p';

UPDATE products SET
  featured_image = '/products/spytec/charger/img_1.jpg',
  gallery_images = '["/products/spytec/charger/img_1.jpg","/products/spytec/charger/img_2.png","/products/spytec/charger/img_3.jpg","/products/spytec/charger/img_4.jpg","/products/spytec/charger/img_5.jpg"]'
  WHERE slug = 'usb-wall-charger-spy-camera-wifi';

UPDATE products SET
  featured_image = '/products/spytec/clock/img_1.jpg',
  gallery_images = '["/products/spytec/clock/img_1.jpg","/products/spytec/clock/img_2.jpg","/products/spytec/clock/img_3.jpg","/products/spytec/clock/img_4.jpg","/products/spytec/clock/img_5.jpg"]'
  WHERE slug = 'wall-clock-spy-camera-1080p-wifi';

UPDATE products SET
  featured_image = '/products/rf-detectors/camdetector/img_1.jpg',
  gallery_images = '["/products/rf-detectors/camdetector/img_1.jpg","/products/rf-detectors/camdetector/img_2.jpg","/products/rf-detectors/camdetector/img_3.jpg","/products/rf-detectors/camdetector/img_4.jpg","/products/rf-detectors/camdetector/img_5.jpg"]'
  WHERE slug = 'wireless-hidden-camera-detector-wifi-spy';

UPDATE products SET
  featured_image = '/products/smartphones/xiaomi14pro/img_1.jpg',
  gallery_images = '["/products/smartphones/xiaomi14pro/img_1.jpg","/products/smartphones/xiaomi14pro/img_2.jpg","/products/smartphones/xiaomi14pro/img_3.jpg","/products/smartphones/xiaomi14pro/img_4.jpg"]'
  WHERE slug = 'xiaomi-14-pro-512gb';


-- ═══════════════════════════════════════════════════════════════════════
-- GPS TRACKER PRODUCT IMAGE FIXES
-- Fixes: mixed images across models, flat-file paths upgraded to
-- proper per-model subfolders (1 main + up to 4 gallery images each).
-- ═══════════════════════════════════════════════════════════════════════

-- ── Yuntrack CJ220 (was wrongly showing CJ780 images) ──────────────────
UPDATE products SET
  featured_image = '/products/gps/cj220/img_1.jpg',
  gallery_images = '["/products/gps/cj220/img_1.jpg","/products/gps/cj220/img_2.jpg"]'
  WHERE slug = 'yuntrack-cj220-4g-gps-tracker';

-- ── Yuntrack CJ280 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/cj280/img_1.jpg',
  gallery_images = '["/products/gps/cj280/img_1.jpg","/products/gps/cj280/img_2.jpg"]'
  WHERE slug = 'yuntrack-cj280-4g-gps-tracker';

-- ── Yuntrack CJ720 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/cj720/img_1.jpg',
  gallery_images = '["/products/gps/cj720/img_1.jpg"]'
  WHERE slug = 'yuntrack-cj720-4g-gps-tracker';

-- ── Yuntrack CJ750 (upgraded: was flat file, now 5-image subfolder) ────
UPDATE products SET
  featured_image = '/products/gps/cj750/img_1.jpg',
  gallery_images = '["/products/gps/cj750/img_1.jpg","/products/gps/cj750/img_2.jpg","/products/gps/cj750/img_3.jpg","/products/gps/cj750/img_4.jpg","/products/gps/cj750/img_5.jpg"]'
  WHERE slug = 'yuntrack-cj750-obd-gps-tracker';

-- ── Yuntrack CJ780 (upgraded: was flat file, now 5-image subfolder) ────
UPDATE products SET
  featured_image = '/products/gps/cj780/img_1.jpg',
  gallery_images = '["/products/gps/cj780/img_1.jpg","/products/gps/cj780/img_2.jpg","/products/gps/cj780/img_3.jpg","/products/gps/cj780/img_4.png","/products/gps/cj780/img_5.png"]'
  WHERE slug = 'yuntrack-cj780-4g-gps-tracker';

-- ── Yuntrack CJ790D (upgraded: was flat file, now 5-image subfolder) ───
UPDATE products SET
  featured_image = '/products/gps/cj790d/img_1.jpg',
  gallery_images = '["/products/gps/cj790d/img_1.jpg","/products/gps/cj790d/img_2.jpg","/products/gps/cj790d/img_3.jpg","/products/gps/cj790d/img_4.jpg","/products/gps/cj790d/img_5.jpeg"]'
  WHERE slug = 'yuntrack-cj790d-4g-fleet-gps-tracker';

-- ── Yuntrack LK208 (upgraded: was flat file, now 5-image subfolder) ────
UPDATE products SET
  featured_image = '/products/gps/lk208/img_1.jpg',
  gallery_images = '["/products/gps/lk208/img_1.jpg","/products/gps/lk208/img_2.jpg","/products/gps/lk208/img_3.jpg","/products/gps/lk208/img_4.jpg","/products/gps/lk208/img_5.jpg"]'
  WHERE slug = 'yuntrack-lk208-personal-gps-tracker';

-- ── Yuntrack LK930 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/lk930/img_1.jpg',
  gallery_images = '["/products/gps/lk930/img_1.jpg"]'
  WHERE slug = 'yuntrack-lk930-4g-gps-tracker';

-- ── Micodus G20 (upgraded: was flat file, now subfolder) ───────────────
UPDATE products SET
  featured_image = '/products/gps/g20/img_1.jpg',
  gallery_images = '["/products/gps/g20/img_1.jpg","/products/gps/g20/img_2.jpg","/products/gps/g20/img_3.jpg"]'
  WHERE slug = 'micodus-g20-magnetic-gps-tracker';

-- ── Micodus G20M (was showing G20 images — now uses its own subfolder) ─
UPDATE products SET
  featured_image = '/products/gps/g20m/img_1.jpg',
  gallery_images = '["/products/gps/g20m/img_1.jpg","/products/gps/g20m/img_2.jpg","/products/gps/g20m/img_3.jpg","/products/gps/g20m/img_4.png"]'
  WHERE slug = 'micodus-g20m-extended-battery-gps-tracker';

-- ── Micodus MV710G Fuel Tracker (upgraded: was using g20 flat file) ────
UPDATE products SET
  featured_image = '/products/gps/g20/img_1.jpg',
  gallery_images = '["/products/gps/g20/img_1.jpg","/products/gps/g20/img_2.jpg","/products/gps/g20/img_3.jpg"]'
  WHERE slug = 'micodus-mv710g-4g-fuel-gps-tracker';

-- ── Micodus GT06 Mini (upgraded: was flat file, now 5-image subfolder) ─
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'micodus-gt06-mini-gps-tracker';

-- ── Micodus GT06 TK200 (upgraded: was flat file, now subfolder) ─────────
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'micodus-gt06-tk200-4g-gps-tracker';

-- ── Micodus GT02D (upgraded: was flat file, now subfolder) ──────────────
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'micodus-gt02d-4g-gps-tracker';

-- ── Micodus GT02-T3 (upgraded: was flat file, now subfolder) ────────────
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'micodus-gt02-t3-4g-gps-tracker';

-- ── SinoTrack ST900 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/st900.jpg',
  gallery_images = '["/products/gps/st900.jpg","/products/gps/st900_2.jpg"]'
  WHERE slug = 'sinotrack-st900-4g-gps-tracker';

-- ── SinoTrack ST815 (was wrongly showing ST900 images — now uses ST915) ─
UPDATE products SET
  featured_image = '/products/gps/st915/img_1.jpg',
  gallery_images = '["/products/gps/st915/img_1.jpg"]'
  WHERE slug = 'sinotrack-st815-4g-gps-tracker';

-- ── SinoTrack ST903 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/st903/img_1.jpg',
  gallery_images = '["/products/gps/st903/img_1.jpg"]'
  WHERE slug = 'sinotrack-st903-gps-tracker';

-- ── SinoTrack ST904 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/st904/img_1.jpg',
  gallery_images = '["/products/gps/st904/img_1.jpg"]'
  WHERE slug = 'sinotrack-st904-gps-tracker';

-- ── SinoTrack ST915 ─────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/st915/img_1.jpg',
  gallery_images = '["/products/gps/st915/img_1.jpg"]'
  WHERE slug = 'sinotrack-st915-gps-tracker';

-- ── 365GPS GF21 (upgraded: was flat file, now 5-image subfolder) ────────
UPDATE products SET
  featured_image = '/products/gps/gf21/img_1.jpg',
  gallery_images = '["/products/gps/gf21/img_1.jpg","/products/gps/gf21/img_2.jpg","/products/gps/gf21/img_3.jpg","/products/gps/gf21/img_4.jpg","/products/gps/gf21/img_5.jpg"]'
  WHERE slug = '365gps-gf21-mini-gps-tracker';

-- ── 360GPS GF21 (upgraded: same hardware as 365GPS GF21 variant) ────────
UPDATE products SET
  featured_image = '/products/gps/gf21/img_1.jpg',
  gallery_images = '["/products/gps/gf21/img_1.jpg","/products/gps/gf21/img_2.jpg","/products/gps/gf21/img_3.jpg","/products/gps/gf21/img_4.jpg","/products/gps/gf21/img_5.jpg"]'
  WHERE slug = '360gps-gf21-mini-gps-tracker';

-- ── 365GPS GF07 ─────────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/gf07/img_1.jpg',
  gallery_images = '["/products/gps/gf07/img_1.jpg","/products/gps/gf07/img_2.jpg"]'
  WHERE slug = '365gps-gf07-mini-gps-tracker';

-- ── Wanway S20 Motorcycle (upgraded: now uses all 4 flat images) ─────────
UPDATE products SET
  featured_image = '/products/gps/s20.jpg',
  gallery_images = '["/products/gps/s20.jpg","/products/gps/s20_2.jpg","/products/gps/s20_3.jpg","/products/gps/s20_4.jpg"]'
  WHERE slug = 'wanway-s20-4g-motorcycle-gps-tracker';

-- ── Wanway GS900 ────────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/gs900.png',
  gallery_images = '["/products/gps/gs900.png"]'
  WHERE slug = 'wanway-gs900-motorcycle-gps-tracker';

-- ── Goome GM06NW (upgraded: includes both flat images) ──────────────────
UPDATE products SET
  featured_image = '/products/gps/gm06nw.jpg',
  gallery_images = '["/products/gps/gm06nw.jpg","/products/gps/gm06nw_2.jpg"]'
  WHERE slug = 'goome-gm06nw-motorcycle-gps-tracker';

-- ── Garmin eTrex ────────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/garmin_etrex/img_1.jpg',
  gallery_images = '["/products/gps/garmin_etrex/img_1.jpg","/products/gps/garmin_etrex/img_2.jpg"]'
  WHERE slug = 'garmin-etrex-10-handheld-gps';

-- ── CarePro TD02S Kids Smartwatch ────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/td02s.jpg',
  gallery_images = '["/products/gps/td02s.jpg"]'
  WHERE slug = 'carepro-td02s-kids-gps-smartwatch';

-- ── Geem Orange 2.0 (5-image upgrade with both available flat images) ───
UPDATE products SET
  featured_image = '/products/gps/orange_sim.jpg',
  gallery_images = '["/products/gps/orange_sim.jpg","/products/gps/orange_sim2.jpg"]'
  WHERE slug = 'geem-orange-2-gps-tracker-4g-lte';

-- ── Geem Orange v1 ──────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/orange_sim.jpg',
  gallery_images = '["/products/gps/orange_sim.jpg","/products/gps/orange_sim2.jpg"]'
  WHERE slug = 'geem-orange-gps-tracker-4g';

-- ── Yuntrack TK905 ──────────────────────────────────────────────────────
UPDATE products SET
  featured_image = '/products/gps/tk905/img_1.jpg',
  gallery_images = '["/products/gps/tk905/img_1.jpg"]'
  WHERE slug = 'yuntrack-tk905-gps-tracker';

-- ── IoT Universal GPS Tracker (upgraded: flat gt06 → gt06 subfolder) ───
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'iot-universal-4g-gps-tracker';

-- ── P31 Portable Personal GPS (upgraded: flat lk208 → lk208 subfolder) ─
UPDATE products SET
  featured_image = '/products/gps/lk208/img_1.jpg',
  gallery_images = '["/products/gps/lk208/img_1.jpg","/products/gps/lk208/img_2.jpg","/products/gps/lk208/img_3.jpg","/products/gps/lk208/img_4.jpg","/products/gps/lk208/img_5.jpg"]'
  WHERE slug = 'p31-portable-personal-gps-tracker';

-- ── N9 GSM GPS Tracker (upgraded: flat gt06 → gt06 subfolder) ───────────
UPDATE products SET
  featured_image = '/products/gps/gt06/img_1.jpg',
  gallery_images = '["/products/gps/gt06/img_1.jpg","/products/gps/gt06/img_2.jpg","/products/gps/gt06/img_3.jpg","/products/gps/gt06/img_4.jpg","/products/gps/gt06/img_5.jpg"]'
  WHERE slug = 'n9-gsm-4g-gps-tracker';

COMMIT;
-- End: 42 products + 35 GPS tracker products updated
